### ISSUE TITLE
Incorporating glmpca into a scanpy pipeline/workflow

### ISSUE THREAD

**Issue by arutik** [willtownes/glmpca-py#10]
Hi,

As I understand right now glmpca is a standalone package and is not integrated in scanpy workflow. Therefore how (at which step) would you advise to use it within the following established workflow?

- Filtering genes and cells
- Normalising & log transforming (I assume this would have to be replaced)
- HVG subsetting
- Scaling
- Calculating PCA
- Building neighborhood graph 
- Calculating UMAP
- Performing unbiased clustering

Thanks.

**Comment by willtownes** [comment]
Yes, that is correct it has not yet been integrated. The input to glmpca is raw UMI counts for the informative features and the output is a set of low-dimensional factors and loadings analogous to PCA. So you would need to do QC filtering of cells and genes as well as feature selection (what you refer to as HVG subsetting) before glmpca. 

Please note that we recommend using deviance as the feature selection criterion rather than HVG since it operates on raw counts and is more consistent with the glmpca model. An R implementation is available here: https://github.com/kstreet13/scry/blob/master/R/featureSelection.R but we have not yet created the python implementation. The deviance functions are very simple though so it shouldn't be too difficult once we get around to it. 

Also, I am planning to change the glmpca function's API and improve the speed and scalability to larger datasets. Based on that you may wish to hold off on integrating it with scanpy for a while until these improvements are released and the API is more stable. I would not want to cause you all problems by breaking backward compability.

**Comment by willtownes** [comment]
Some of the motivation for the future API changes is described in #7

**Comment by arutik** [comment]
I see, thank you.
I have some follow up questions: 
1) if I use glmpca after feature selection, then should I omit step 2 (Normalising & log transforming)? Or just use the raw matrix?
2) do I understand correctly that after glmpca the data may be passed on to the following steps (Building neighborhood graph, Calculating UMAP etc.) with no further changes?

**Comment by willtownes** [comment]
1. You should pass the raw UMI counts matrix with only selected features to glmpca.
2. I'm not sure how scanpy computes the neighborhood graph and UMAP etc, but my guess is it uses the top X principal components to compute distances or to initialize UMAP rather than the data itself. If so, you can just use the "factors" from glmpca with L=X instead of the top X PCs for the same purpose.

**Comment by arutik** [comment]
Thanks, I see. Would be great to have it incorporated into scanpy in the future, for ease of use.
