### ISSUE TITLE
Feature request: Fixing nb.theta during optimization

### ISSUE THREAD

**Issue by jlause** [willtownes/glmpca-py#11]
Hey Will,

thanks for porting this package from R to python! I have a small request:

I work in a setting where the NB theta parameter is known, and I don't want to estimate it from the data in some circumstances. Instead, I just want to pass it an leave it fixed. I made that work by adding a new flag variable to `glmpca()`'s inputs, and skipping the optimization update for theta depending on that flag, replacing [this line](https://github.com/willtownes/glmpca-py/blob/58ce7b609751a8b9e4828abc4f5aa4b2576298af/glmpca/glmpca.py#L372)

by

```
if fam=="nb":
    if optimize_nb_theta:
        nb_theta= est_nb_theta(Y,gf.family.link.inverse(rfunc(U,V)),nb_theta)
```

If you think that makes sense, I'd be happy to see it in the official code :) If I can help let me know.

Best, Jan.

**Comment by dkobak** [comment]
It could also be defined as `fam='nb3'` maybe? or `nb-fixed` or something.

**Comment by willtownes** [comment]
@jlause that's a good idea. I would prefer to have the flag passed in as a control parameter (an element of the dictionary `ctl`) rather than adding another option to the `fam` argument. It will probably be a while before I can get around to it, so if you don't mind doing a pull request that would probably speed up the process. Ideally it would also be nice to have a unit test that checks the passed-in value doesn't get changed in the returned object when the flag is set.
