### ISSUE TITLE
Sanity Check

### ISSUE THREAD

**Issue by batson** [willtownes/glmpca-py#2]
Playing around with this, and I want to make sure I'm interpreting things correctly.

If I have an integer matrix `Y`, and write

`output = glmpca.glmpca(Y, 10)`,

then corresponding glm is `Y ~ Poisson(M)` with

`M = np.exp(output['loadings'].dot(output['factors'].T) + output['coefX'].`

One could compare to a baseline linear model based on direct SVD, with a constant offset epsilon to keep from predicting hard zeroes.

```
U, S, V = randomized_svd(np.sqrt(Y), 10)
projected = (np.maximum(0, U.dot(np.diag(S)).dot(V)))**2
M = projected + 0.01
```
In some quick experiments on real scRNA-seq data, I was getting smaller likelihoods/deviances from the latter model than from `glmpca`. I'm wondering if this is because `glmpca` isn't converging to an optimal solution (does it have guarantees?) or if M = exp(UV) is a weaker model for this data than M = max(UV, 0)**2 + eps is.

**Comment by willtownes** [comment]
Thanks for this interesting comparison! Are you using the Poisson deviance for both "M"s? If not, it can be retrieved from glmpca output by `res["glmpca_family"].family.deviance`. And is "umis" the same as "Y"? Also, in your equation for the predicted mean matrix from glmpca it is missing the offset vector (**note to self- make this more clear in the documentation**). It should be something like:

```python
offsets = np.log(Y.mean(0))
M = np.exp(output['loadings'].dot(output['factors'].T) + output['coefX']+offsets)
```

Technically the link function is not the pure log since I am trying to build on the statsmodels package and they do some clipping to avoid taking logs of zeros but that shouldn't make too big of a difference. You can access the actual link function from `output["glmpca_family"].family.link` which should behave similarly to log and the inverse from `output["glmpca_family"].family.link.inverse` which should behave similarly to exp.

Would it be helpful if I provide an explicit function in the package to generate the "M" matrix? And maybe also to expose the deviance function more clearly to facilitate comparisons like these with other "M" matrices that are not produced by glmpca?

**Comment by batson** [comment]
`umis` is the same as `Y`, and, to be explicit, I was using the poisson log-likelihood

`(M - Y.dot(np.log(M)).sum()`

which should be the deviance up to a constant. I definitely did not know about the offsets...I had somehow assumed that was what the intercept term in the `output['coefX']` was doing. (With no covariates `X`, there is one nonzero col in `coefX`.) Do the offsets go per column and the intercepts per-row?

It would definitely be helpful to have the `M` matrix, so that we can use `glmpca` as a denoiser and compare across models.

**Comment by batson** [comment]
If I run

```
output = glmpca.glmpca(Y, 10, penalty=0, fam='poi', verbose=True)
offsets = np.log(Y.mean(0))
M = np.exp(output['loadings'].dot(output['factors'].T) + output['coefX'] + offsets)
```

then the deviance/loglik is better for `glmpca` than for the heuristic shifted svd i shared above.

Am I correct that `output['coefX']` is a per-row intercept and `offsets` is a per-column intercept? The former is fit by the optimization and the latter is set a priori to the log mean?

**Comment by willtownes** [comment]
I'm glad to hear that improved the deviance. Yes, you are correct, the offsets is a vector aligned with columns (observations/cells) of the data matrix and it doesn't change during optimization. In fact you can set the offsets using size factors from other methods such as scran by using the `sz` argument to glmpca. The offsets are produced by applying the link function to `sz`. If sz is set to None, the default is to use the column means as this mimics the "n" in the multinomial model (ie the column sums). We just use the mean instead of sum because it's more stable numerically. The goal of sz and offsets is to absorb cell-to-cell differences in capture efficiency/ reverse transcriptase that would otherwise confound the downstream analysis. It's basically analogous to normalization except it's integrated into the model rather than a preprocessing transformation.

Also you are correct that `output['coefX']` is a per-row intercept. It is meant to absorb variation resulting from individual genes just globally being more highly expressed across all cells. It is analogous to centering features before applying PCA. If `X` is not None in the input, the dimensionality of `output['coefX']` will be ncol(X)+1. The first column will still be this per-gene intercept term, but the remaining columns will be per-gene coefficients for the covariates in the columns of X. This could be useful for removing batch effects, as you could use a dummy variable for batch membership and have coefX absorb the effect, removing it from the latent variables U and V. However, we haven't explored how effective this is very thoroughly yet.

I definitely need to make all of this more clear in the documentation.
